version: "3.8"

services:
  pg-shard-1:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: aether
      POSTGRES_PASSWORD: aether_password
      POSTGRES_DB: aether
    ports:
      - "5432:5432"
    volumes:
      - pg-shard-1-data:/var/lib/postgresql/data
      - ../postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aether"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg-shard-2:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: aether
      POSTGRES_PASSWORD: aether_password
      POSTGRES_DB: aether
    ports:
      - "5433:5432"
    volumes:
      - pg-shard-2-data:/var/lib/postgresql/data
      - ../postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aether"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg-shard-3:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: aether
      POSTGRES_PASSWORD: aether_password
      POSTGRES_DB: aether
    ports:
      - "5434:5432"
    volumes:
      - pg-shard-3-data:/var/lib/postgresql/data
      - ../postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aether"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic aether.tasks.dlq --replication-factor 1 --partitions 3
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  pg-shard-1-data:
  pg-shard-2-data:
  pg-shard-3-data:
